import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientCesiumConfig from "./ClientCesiumConfig";
import { cn } from "@/lib/utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn(geistSans.variable, geistMono.variable, "antialiased")}>
        {/* ini jalan di client untuk set CESIUM_BASE_URL */}
        <ClientCesiumConfig />
        {children}
      </body>
    </html>
  );
}
